from pathlib import Path

from pptx import Presentation

from pptx.util import Inches, Pt


class PPTExporter:

    def export(
        self,
        state,
        output_path,
    ):

        Path(output_path).parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        report = state["slide_content"]

        prs = Presentation()

        # -----------------------------
        # Cover Slide
        # -----------------------------

        cover = prs.slide_layouts[0]

        slide = prs.slides.add_slide(
            cover
        )

        slide.shapes.title.text = (
            f"{state['ticker']} Research Report"
        )

        slide.placeholders[1].text = (
            "Generated by AI Company Evaluator"
        )

        # -----------------------------
        # Parse Report
        # -----------------------------

        sections = []

        current_title = None

        current_content = []

        for line in report.split("\n"):

            if line.startswith("# "):

                if current_title:

                    sections.append(

                        (
                            current_title,
                            "\n".join(
                                current_content
                            ),
                        )

                    )

                current_title = line.replace(
                    "# ",
                    "",
                )

                current_content = []

            else:

                current_content.append(
                    line
                )

        if current_title:

            sections.append(

                (
                    current_title,
                    "\n".join(
                        current_content
                    ),
                )

            )

        # -----------------------------
        # Create Slides
        # -----------------------------

        for title, content in sections:

            layout = prs.slide_layouts[1]

            slide = prs.slides.add_slide(
                layout
            )

            slide.shapes.title.text = (
                title
            )

            textbox = slide.shapes.placeholders[
                1
            ]

            tf = textbox.text_frame

            tf.clear()

            p = tf.paragraphs[0]

            p.text = content

            p.font.size = Pt(
                9
            )

        prs.save(
            output_path
        )